dist: xenial
language: python
services:
  - xvfb
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"

matrix:
  allow_failures:
    python: "nightly"

# command to run tests
script: python setup.py test
