dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
  - "pypy"
  - "pypy3"

matrix:
  allow_failures:
    python: "nightly"

# command to run tests
script: python setup.py test
